name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v2.3.1
        with:
          release-type: "node"
          package-name: "my-package"
          github-token: ${{ secrets.GITHUB_TOKEN }
